name: Build
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        required: false
        default: 'Mona the Octocat'

jobs:
  build:
    runs-on: ubuntu-latest
    name: proxy
    steps:
      - run: |
          echo "Hello, World"
